Softbucks/Controllers/AdministratorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SoftBucksBase.Models;
using SoftBucksBase.DAO;
using Microsoft.AspNet.Identity;



namespace Softbucks.Controllers
{
    public class AdministratorController : Controller
    {
        private UnitOfWork _UoW = new UnitOfWork();
        
        [Authorize(Roles = "admin")]
        public ActionResult Index()
        {
            return View();    
        }

        public ActionResult GetDataBeverage ()
        {     
            IEnumerable<Beverage> bev = _UoW.BeverageDAO.getAll().ToList();
            return Json(bev, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetDataCondiment()
        {
            IEnumerable<Condiment> Condiments = _UoW.CondimentDAO.getAll().ToList();
            return Json(Condiments, JsonRequestBehavior.AllowGet);
        }

        #region CRUDBeverage
        [HttpPost]
        public void CreateBeverage(Beverage bev)
        {
            bev.Id = _UoW.BeverageDAO.GetNextId();
            _UoW.BeverageDAO.create(bev);
            _UoW.Commit();     
        }

        [HttpPost]
        public void DeleteBeverage(int id)
        {
            Beverage tempBev = _UoW.BeverageDAO.FindById(id);
            _UoW.BeverageDAO.delete(tempBev);
            _UoW.Commit();
        }

        [HttpPost]
        public void EditBeverage(Beverage bev)
        {
            _UoW.BeverageDAO.update(bev);
            _UoW.Commit();
        }
        #endregion

        #region CRUDCondiment
        [HttpPost]
        public void CreateCondiment(Condiment condiment)
        {
            condiment.Id = _UoW.CondimentDAO.GetNextId();
            _UoW.CondimentDAO.create(condiment);
            _UoW.Commit();
        }

        [HttpPost]
        public void DeleteCondiment(int id)
        {
            Condiment tempCondiment = _UoW.CondimentDAO.FindById(id);
            _UoW.CondimentDAO.delete(tempCondiment);
            _UoW.Commit();
        }

        [HttpPost]
        public void EditCondiment(Condiment condiment)
        {
            _UoW.CondimentDAO.update(condiment);
            _UoW.Commit();
        }
        #endregion
        protected override void Dispose(bool disposing)
        {
            _UoW.Dispose();
            base.Dispose(disposing);
        }
    }
}

Softbucks/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title – приложение ASP.NET</title>

    @Scripts.Render("~/bundles/jquery")
   
    <script src="~/Scripts/i18n/grid.locale-ru.js"></script>
    
   

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body class="cbody">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container1">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
              
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Домашняя страница", "Index", "Home")</li>
                    <li>@Html.ActionLink("Администратор", "Index", "Administrator")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year – приложение ASP.NET</p>
        </footer>
    </div>

    @RenderSection("scripts", required: false)
</body>
</html>